name: CodeMagePython
main: org.gamestartschool.codemage.python.CodeMagePythonSpigotPlugin
version: 1.0.0
commands:
  python:
    description: Run python command
    usage: |
      /python
  blink:
    description: Run blink command
    usage: |
      /bl